# Generated by Django 3.2 on 2022-11-12 13:39

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articlePags',
            fields=[
                ('uuids', models.UUIDField(auto_created=True, verbose_name='UUID')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('articletype', models.CharField(choices=[('m', 'md'), ('r', 'href')], default='md', max_length=49, verbose_name='记录类型')),
                ('urlshref', models.CharField(blank=True, max_length=999, null=True, verbose_name='链接')),
                ('mdtext', mdeditor.fields.MDTextField(blank=True, default='', null=True, verbose_name='内容')),
                ('text', models.TextField(verbose_name='简介')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('ifok', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='filelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('file', models.FileField(blank=True, null=True, upload_to='upload_file/', verbose_name='文件')),
            ],
            options={
                'verbose_name': '文件列表',
                'verbose_name_plural': '文件列表',
            },
        ),
    ]
